
services:
  - name: docker:20.10-dind
    alias: docker

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  APP_ENV: 'local'
  APP_URL: http://127.0.0.1:8000
  DASHBOARD_URL: http://127.0.0.1:80
  DB_CONNECTION: 'mysql'
  DB_HOST: 'database'
  DB_PORT: '3306'
  DB_DATABASE: 'mailing_service'
  MAIL_MAILER: 'smtp'
  MAIL_FROM_NAME: 'Mailing_Service'

stages:
  - test

before_script:
  # Update package lists and install dependencies
  - apt-get update
  - apt-get install -y wget gnupg libpng-dev libjpeg-dev libfreetype6-dev libxml2-dev libonig-dev libicu-dev libxslt-dev zlib1g-dev libzip-dev unzip

  # Install Docker CLI
  - curl -fsSL https://get.docker.com | sh

  # Install Docker Compose
  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - docker --version # Verify Docker installation
  - docker-compose --version # Verify Docker Compose installation

  # Install Google Chrome dependencies and Chrome
  - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
  - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - apt-get update
  - apt-get install -y google-chrome-stable
  - google-chrome --version # Verify Chrome installation

test:
  stage: test
  image: node:lts
  script:
    - npm install
    - docker compose up -d
    - sleep 40
    - docker compose ps
    - docker compose logs app
    # - npx mocha testcase/test_sendemail_javascript.spec.cjs
  after_script:
    - docker compose down

  # In CI/CD Variables
  # DB_USERNAME: 'group3'
  # DB_PASSWORD: '87654321'
  # MAIL_HOST: 'sandbox.smtp.mailtrap.io'
  # MAIL_PORT: '2525'
  # MAIL_USERNAME: '411b1cc4d89ccf'
  # MAIL_PASSWORD: '3062cdc807ffc5'
  # MAIL_ENCRYPTION: ''
  # MAIL_FROM_ADDRESS: 'hello@example.com'


