apiVersion: v1
kind: ConfigMap
metadata:
  name: config-env
data:
  DASHBOARD_URL: "http://127.0.0.1:80"
  APP_NAME: "Mailing Service"
  APP_ENV: "local"
  APP_DEBUG: "true"
  APP_URL: "http://127.0.0.1:8081"
  DB_CONNECTION: "mysql"
  DB_HOST: "database"
  DB_PORT: "3306"
  DB_DATABASE: "mailing_service"
  DB_USERNAME: "group3"
  MAIL_MAILER: "smtp"
  MAIL_HOST: "Mailtrap_Service"
  MAIL_PORT: "1025"
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "hello@example.com"
  MAIL_FROM_NAME: "Group 3"
