apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  labels:
    app: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
      - name: laravel-container
        image: danish3321/laravel-service:v1
        imagePullPolicy: Always
        env:
        - name: DASHBOARD_URL
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: DASHBOARD_URL
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: APP_NAME
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: APP_ENV
        - name: APP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: APP_DEBUG
        - name: APP_URL
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: APP_URL
        - name: DB_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: DB_CONNECTION
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: DB_PASSWORD
        - name: MAIL_MAILER
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: MAIL_MAILER
        - name: MAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: MAIL_HOST
        - name: MAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: MAIL_PORT
        - name: MAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: MAIL_USERNAME
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: MAIL_PASSWORD
        - name: MAIL_ENCRYPTION
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: MAIL_ENCRYPTION
        - name: MAIL_FROM_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: MAIL_FROM_ADDRESS
        - name: MAIL_FROM_NAME
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: MAIL_FROM_NAME
        ports:
          - containerPort: 8081
        command:
          - sh
          - -c
          - |
            php artisan key:generate &&
            php artisan migrate &&
            php artisan config:clear &&
            php artisan cache:clear &&
            php artisan config:cache &&
            php artisan serve --host=0.0.0.0 --port=8081
        # livenessProbe:
        #   httpGet:
        #     path: /liveness-check         # Path for the liveness probe
        #     port: 80              # Port your application is listening on
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /readiness-check       # Path for the readiness probe
        #     port: 80              # Port your application is listening on
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  type: LoadBalancer
  selector:
    app: laravel-app
  ports:
  - name: laravel-service-port
    protocol: TCP
    port: 8081
    targetPort: 8081
